# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a8aa6a36b3bd9b4c444f4b07ac03abe9421293bd97dc7d84dcfd76c1443ebbadd118e81378e9931dc830f1200b6d90c54e49551bf101a2cdf3deec198f7732f3

test:
  secret_key_base: e3ad8ac41f056f8cd46c84fa72ddddc9e985c2c425d787739118891f642e9b4df98dd7315e2eef665ab9d85e1eb175d8688fa7d1cb50c85eea163bf1735d638b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
